### ISSUE TITLE
Exporting statistics in csv format backend

### ISSUE THREAD

**Issue by JaanJanno** [JaanJanno/ConsultationWeb#101]
Functional requirement 21
https://github.com/JaanJanno/ConsultationWeb/wiki/Functional-requirements-and-vision

**Comment by TKasekamp** [comment]
Only include consultations that have a student feedback.

**Comment by TKasekamp** [comment]
Include consultations where student feedback isn't present, but the meeting was at least 30 days ago.

**Comment by TKasekamp** [comment]
Considering the issue closed. The current export is enough for the client.
