### ISSUE TITLE
Set meeting page view

### ISSUE THREAD

**Issue by TKasekamp** [JaanJanno/ConsultationWeb#113]
Should display calendar and form to set a meeting. @JaanJanno will add the picture.

Calendar width 9 col, form width 3 col.

Req 9
https://github.com/JaanJanno/ConsultationWeb/wiki/Functional-requirements-and-vision

**Comment by TKasekamp** [comment]
Consultation details are in the object `consultation`. Take a look at the controller from #114

**Comment by JaanJanno** [comment]
This view gonna exist on URL: /requests/{id}/setmeeting
![20161110_130639](https://cloud.githubusercontent.com/assets/5450973/20174593/47d89be0-a747-11e6-898e-b2c3f67a29c3.jpg)

**Comment by TKasekamp** [comment]
The set meeting box isn't polished enough. The set date should use the date/time setter from the Miminium theme.

Also, the grey stripe in the calendar panel isn't needed.

**Comment by salman-** [comment]
Please add the date time picker.
