### ISSUE TITLE
Button for setting feedback for status "SCHEDULED"

### ISSUE THREAD

**Issue by JaanJanno** [JaanJanno/ConsultationWeb#116]
When request status is "SCHEDULED", the list and details view should show a "Set feedback" button.
Pressing it will lead to URL: "/requests/{id}/consultantfeedback"

**Comment by salman-** [comment]
@JaanJanno  which list sdo u mean?
can u give me the uri?

if u mean the **/requests** it only loads the **RECEIVED** requests.

**Comment by TKasekamp** [comment]
The list at /requests/scheduled. It doesn't maybe exist, so add a controller and view.  That's probably what @JaanJanno meant.

**Comment by salman-** [comment]
@TKasekamp  looks like it's ok!!!
Please double check it, and if it's ok ,close it.
