### ISSUE TITLE
Calendar JS refactor

### ISSUE THREAD

**Issue by TKasekamp** [JaanJanno/ConsultationWeb#122]
Make calendar JS into separate fragment.

**Comment by TKasekamp** [comment]
For the statistcs page, the calendar is now in a separate JS file. For the set meeting page, you can edit that JS file to create a method that creates the calendar and pass it an evenSource so you don't have to add events to Thymeleaf. So the eventSource would be `/api/calendar/{consultantId}`. And then add the statistics.js file as a src for meetings page.

**Comment by salman-** [comment]
I reviewed the code and it was not possible. You can do this refactor if you want it.
