### ISSUE TITLE
Consultation request load test

### ISSUE THREAD

**Issue by TKasekamp** [JaanJanno/ConsultationWeb#131]
Test with Selenium on the Heroku production server. POST an absurd amount of requests and record the time it takes to complete each POST. For proof, make a table of each request time and the average time (some other statistics etc. Go nuts). At the end, put a screenshot of the requests in the system.

**Comment by JaanJanno** [comment]
![screenshot 73](https://cloud.githubusercontent.com/assets/5450973/20796037/ec0755f8-b7dc-11e6-87fb-10beb6cd0a06.png)

**Comment by JaanJanno** [comment]
Created in wiki page:
https://github.com/JaanJanno/ConsultationWeb/wiki/Load-test
