### ISSUE TITLE
Browser compatibility non-functional requirement test

### ISSUE THREAD

**Issue by TKasekamp** [JaanJanno/ConsultationWeb#133]
Test that the application works as specified in a non-func req. Make a wiki page, include a screenshot of the index page for each browser. Fix problems if needed.

**Comment by salman-** [comment]
why did u open it, with no comment?

**Comment by TKasekamp** [comment]
There should be a separate page for this test, but I can't find it in the wiki.

**Comment by TKasekamp** [comment]
@salman- why did you assign me? This is your job.

**Comment by salman-** [comment]
![chrome](https://cloud.githubusercontent.com/assets/4312244/20868528/5f9a7afa-ba66-11e6-95f7-8035060e0783.jpg)
![firefox](https://cloud.githubusercontent.com/assets/4312244/20868527/5f989726-ba66-11e6-81f9-0c6d60b9b8bd.jpg)
![ie](https://cloud.githubusercontent.com/assets/4312244/20868526/5f988a56-ba66-11e6-8eb7-45b5c8bf7f45.jpg)

**Comment by JaanJanno** [comment]
Seems this has been completed. Closing.
