### ISSUE TITLE
Write use case verification walkthrough

### ISSUE THREAD

**Issue by TKasekamp** [JaanJanno/ConsultationWeb#147]
At least two use cases (submit consultation request, accept a consultation request) must be manually verified in the wiki. More info [here](https://groups.google.com/forum/#!topic/tvp2016/9K6qhc750o4).

Create a separate wiki page and provide a walkthrough where you test that the use case is actually there.

Has to be done by Sunday.

**Comment by salman-** [comment]
"use case verification walkthrough" page in wiki

**Comment by JaanJanno** [comment]
Please upload these pictures to this issue as comments and link to them from the wiki, instead of adding them to the code repository.

**Comment by salman-** [comment]
- 
![accepted requests](https://cloud.githubusercontent.com/assets/4312244/21079832/c3e2890e-bfa6-11e6-9f5c-d0e50310f9a0.jpg)
![consultant account](https://cloud.githubusercontent.com/assets/4312244/21079835/c3e387f0-bfa6-11e6-9123-1093df2e13fd.jpg)
![log in](https://cloud.githubusercontent.com/assets/4312244/21079834/c3e2ba82-bfa6-11e6-998e-56490a1a2f6c.jpg)
![request](https://cloud.githubusercontent.com/assets/4312244/21079833/c3e2849a-bfa6-11e6-95ff-580a49ec6437.jpg)

**Comment by TKasekamp** [comment]
Write a proper walkthrough. What do those images mean? What use cases do they refer through? What fields are mandatory to fill in? What are the preconditions (there has to be a account)? What is the success message, what is the error message? 

This has to be done properly, we need these points.

**Comment by TKasekamp** [comment]
Seriously, this has to be done today as the deadline is the presentation.

**Comment by salman-** [comment]
[this ](https://github.com/vladislavivanistsev/SuperCap/wiki/_Tests)is the sample, that Marlon has provided.
It has none of the things u mentioned.
If you are insisting on extra details you can make them yourself.

Additionally, the questions that u pointed, are mostly irrelevant.

**Comment by TKasekamp** [comment]
The page you have made is not sufficient. Currently it's just a collection of random screenshots. If I'm a stranger to this project, then what am I looking at? What use cases do these pictures refer to? How do you prove that the functionality described in the use case is actually present?

The link you provided has an explanation for each step with a reference to the use case they're testing.

**Comment by JaanJanno** [comment]
The sample page is broken at the moment. It originally contained linked pictures that have since been removed, so its not much use to take inspiration from it.

**Comment by TKasekamp** [comment]
Are you going to do it or not?

**Comment by JaanJanno** [comment]
![screenshot 24](https://cloud.githubusercontent.com/assets/5450973/21163760/8e97e98a-c19d-11e6-8792-bf7bf5c3dfe4.png)

![screenshot 25](https://cloud.githubusercontent.com/assets/5450973/21163763/9298cc20-c19d-11e6-911c-c576f80546b3.png)

![screenshot 26](https://cloud.githubusercontent.com/assets/5450973/21163767/96e216c4-c19d-11e6-967d-99e9ca7b1ead.png)

![screenshot 27](https://cloud.githubusercontent.com/assets/5450973/21163771/997a27fa-c19d-11e6-82b8-318164e510c8.png)

**Comment by JaanJanno** [comment]
![screenshot 37](https://cloud.githubusercontent.com/assets/5450973/21163786/b38022b2-c19d-11e6-8fdb-941e4bb21736.png)

![screenshot 47](https://cloud.githubusercontent.com/assets/5450973/21163788/b64845c4-c19d-11e6-9862-175af047ed89.png)

![screenshot 48](https://cloud.githubusercontent.com/assets/5450973/21163790/b88eca9c-c19d-11e6-8dbf-6b0cacae0840.png)

![screenshot 49](https://cloud.githubusercontent.com/assets/5450973/21163792/bac31390-c19d-11e6-9c3e-70906083f05c.png)

![screenshot 50](https://cloud.githubusercontent.com/assets/5450973/21163795/bcab6252-c19d-11e6-9fe7-945425719a27.png)

**Comment by JaanJanno** [comment]
Did some improvements. Closing.
