### ISSUE TITLE
Add view for students post-consultation form

### ISSUE THREAD

**Issue by JaanJanno** [JaanJanno/ConsultationWeb#34]
Requirement 3
https://github.com/JaanJanno/ConsultationWeb/wiki/Functional-requirements-and-vision

**Comment by JaanJanno** [comment]
![20161006_113603](https://cloud.githubusercontent.com/assets/5450973/19147574/6853042e-8bc1-11e6-881a-5c67fccd8837.jpg)

**Comment by salman-** [comment]
@TKasekamp  Do the Back-end.

**Comment by salman-** [comment]
you should make an answer for post.

**Comment by TKasekamp** [comment]
Backend is #35 , no need to re-open this.

**Comment by JaanJanno** [comment]
haha
