### ISSUE TITLE
Add view for consultants post-consultation form

### ISSUE THREAD

**Issue by JaanJanno** [JaanJanno/ConsultationWeb#36]
Requirement 14
https://github.com/JaanJanno/ConsultationWeb/wiki/Functional-requirements-and-vision

**Comment by JaanJanno** [comment]
THIS ONE NOW OUTDATED!
![20161006_111837](https://cloud.githubusercontent.com/assets/5450973/19147586/76c05656-8bc1-11e6-9c2f-e1d7c2f89e9a.jpg)

**Comment by JaanJanno** [comment]
![consultantfeedback](https://cloud.githubusercontent.com/assets/5450973/19555160/5898c7d6-96c4-11e6-9880-4c5490a75250.jpg)

**Comment by salman-** [comment]
@JaanJanno  please, describe the options of drop-down elements.

**Comment by salman-** [comment]
@TKasekamp Please handle the response.

**Comment by TKasekamp** [comment]
The backend is #37 and is assigned to @JaanJanno . Closing this issue.
