### ISSUE TITLE
Add view for listing accepted consultation requests

### ISSUE THREAD

**Issue by JaanJanno** [JaanJanno/ConsultationWeb#45]
Should be behind GET URL: /acceptedrequests

Requirement 8
[https://github.com/JaanJanno/ConsultationWeb/wiki/Functional-requirements-and-vision](https://github.com/JaanJanno/ConsultationWeb/wiki/Functional-requirements-and-vision)

**Comment by salman-** [comment]
@TKasekamp you must first handle the back-end for accepted requests,
then you should make a service for getting the requests based on consultant.

**Comment by TKasekamp** [comment]
What is there to be done in the back-end? The page `/requests/ACCEPTED` displays all requests with status accepted for the currently logged in consultant. If you mean the Java code, the service that does that is `ConsulationService.findByStatusAndConsultant(ConsultationStatus status, Account consultant);`

**Comment by salman-** [comment]
It seems that accept button still has some problem, i cannot load the accepted requests.
We can discuss it in meeting.

**Comment by TKasekamp** [comment]
@salman- , I changed the details button from POST to GET, so it no longer works. Take a look at requests.html to see how it is now.

**Comment by salman-** [comment]
Fixed with #68
