### ISSUE TITLE
Improve index page view

### ISSUE THREAD

**Issue by TKasekamp** [JaanJanno/ConsultationWeb#48]
Should have a login button and a link to create a request form. Has to look nice.

**Comment by salman-** [comment]
Your point is not clear.
Do we create form?

**Comment by TKasekamp** [comment]
I vision something like a landing page http://www.wix.com/website/templates/html/landing-pages/1

You don't have to add a picture or anything too fancy. Work with the CSS we currently have. Just remove all the buttons that the can't be actually used (require login). Add a clear title (Welcome to AVOK! or something) and links to the login page and to the consultation request page. Make it look presentable.

**Comment by salman-** [comment]
So, there would be 2 links. 
1- To request form
2- To login
with an extra welcome message

**Comment by TKasekamp** [comment]
Yes, but they need to be big, visible and look nice.

**Comment by TKasekamp** [comment]
The index page will have the logo from AVOK and a stock image (something nice). Buttons to access consulation request form and login page.

**Comment by salman-** [comment]
You can reopen it, when the customer sends the logo. Maybe he will not send it before third iteration
then it is not wise to make a milestone for it.
