### ISSUE TITLE
Create view for admin's statistics page

### ISSUE THREAD

**Issue by JaanJanno** [JaanJanno/ConsultationWeb#54]
![adminstat](https://cloud.githubusercontent.com/assets/5450973/19552117/2c9c2950-96b7-11e6-8cbc-638268823a8b.jpg)

**Comment by JaanJanno** [comment]
Requirement 19
https://github.com/JaanJanno/ConsultationWeb/wiki/Functional-requirements-and-vision

**Comment by salman-** [comment]
Today, Weekly,Monthly  are these tabs or simple links?

**Comment by TKasekamp** [comment]
They are links that will activate an AJAX request to the server to populate the statistics boxes with the time stats.

**Comment by salman-** [comment]
They shouldn't be link. They are either a drop box element or a radio group.

**Comment by TKasekamp** [comment]
Both of those will make the page look uglier. If they are all links then the user can clearly see all the possible time options. Additionally, the currently selected value should be highlighted (by default All/total). 

Take a look at the [this page](http://akivaron.github.io/miminium/) to see what I mean.

**Comment by salman-** [comment]
I have already seen it, the purpose of designer was a different links, and not ajax.
Take a look at the left hand side menu in [this](http://www.varzesh3.com/).

**Comment by salman-** [comment]
What are the charts in the bottom of the page?

**Comment by TKasekamp** [comment]
That's the calendar with a consultant selection dropdown at the top. Make some dummy events for it as the calendar code isn't implemented yet.

If you really want to change the time selection links, then we'll talk about it tomorrow.

**Comment by salman-** [comment]
I tried to set the calnder using the CSS or [this](https://github.com/metronome12/boot-calendar), but i failed to handle it.

**Comment by TKasekamp** [comment]
I can do the calendar if you want me to.

**Comment by salman-** [comment]
Let me try it once more and we can discuss what i did. 
Thx for support

**Comment by TKasekamp** [comment]
The accepted and other numbers are accessible from the view as they are included in the controller. See `StatisticsDTO` for info about the fields.

**Comment by salman-** [comment]
The drop down menu is added in #105
