### ISSUE TITLE
Consultant completed consultations view

### ISSUE THREAD

**Issue by TKasekamp** [JaanJanno/ConsultationWeb#68]
As described in req 27
https://github.com/JaanJanno/ConsultationWeb/wiki/Functional-requirements-and-vision

**Comment by salman-** [comment]
@TKasekamp How do you mention a request has a feedback or not?

**Comment by TKasekamp** [comment]
If feedback object is not null, display YES. Note that there is no feedback object yet.

**Comment by salman-** [comment]
I need the feedback object to complete this and #74

**Comment by salman-** [comment]
req 27 mentions to the admin, but what is the correct uri for the consultant.

**Comment by TKasekamp** [comment]
for consultant /requests/completed.

Also, I have created a CompletedDTO to show in the consultation views. It is probably already put into the completed views. It has a boolean value for both feedbacks. Is that enough to make the view work?

**Comment by salman-** [comment]
I have found ur CompletedDTO class, but it is not exactly what i need.
There is a service **List<CompletedDTO> findCompleted(Account consultant);**

But i need something more specific. I would like to get the feedback for a certain consultation.
So i suggest to have service like this
**CompletedDTO getFeedback(requestId)**

**Comment by TKasekamp** [comment]
As defined in req 27, the view will only contain a YES/NO for a feedback. That's why the `CompletedDTO` has a boolean value for it. It won't contain a link to that feedback, as only the consultation request details page will have the feedbacks. If the view doesn't contain the actual feedback objects, then is that new service really neccessary?

**Comment by JaanJanno** [comment]
Tõnis is correct on that point. This specific view does not need the feedback object at all. What I'm not sure about is the need to have those booleans at all - at least for the consultant it is already implied that ending up in this list means an existant feedback. But for now let's leave them in - not too hard to remove if necessary.

Where the feedback object is needed is the "details" view.
