### ISSUE TITLE
Improve consultation request details page

### ISSUE THREAD

**Issue by TKasekamp** [JaanJanno/ConsultationWeb#74]
Comments rendered as HTML.

Show all data from model.

Also add stuff from req 25
https://github.com/JaanJanno/ConsultationWeb/wiki/Functional-requirements-and-vision

**Comment by salman-** [comment]
@TKasekamp  How can I access to the data of previous or upcoming meeting for a certain request?
I think, currently the app does not support it.

**Comment by TKasekamp** [comment]
You are correct, the ConsultationRequest object does not yet contain info about the previous or next Consultations as I have to think about how to use the Hibernate annotations correctly. Basically avoid an endless reference scenario. 

You only have to check if the next/previous consultation is not null and display a link to that objects detail page. Nothing else is required, I think.

**Comment by TKasekamp** [comment]
The details page now has links to previous and next consultations. But you should also show the status of the request.

Also, the Accept button should be removed if the status is not received.

**Comment by salman-** [comment]
@TKasekamp @JaanJanno  In case that a request still does not have its feedbacks, the detail page should not show them. Am i right?

How does the consultation object support it?
Currently it doesn't have any information regarding feedback.
