### ISSUE TITLE
Back-end for accept button in detail page does not work

### ISSUE THREAD

**Issue by salman-** [JaanJanno/ConsultationWeb#75]
@TKasekamp

**Comment by TKasekamp** [comment]
Same thing as with #76 . Tested it and it works. How exactly is it broken?

**Comment by salman-** [comment]
Make a request, including a comment, and text type and a file.
Now login and try to accept it. Once it is accepted i should disappear from the waiting list.

@TKasekamp  you should test again,

**Comment by TKasekamp** [comment]
The accepted requests are no longer visible at `/requests` and are now only in `/requests/ACCEPTED`. This is what I tested.
