### ISSUE TITLE
Back-end for accept button in index page does not work

### ISSUE THREAD

**Issue by salman-** [JaanJanno/ConsultationWeb#76]
@TKasekamp

**Comment by salman-** [comment]
The page every time loads the request, find the bug and resolve it.

**Comment by salman-** [comment]
It also, has a problem in loading Jackson data.

**Comment by TKasekamp** [comment]
How exactly is it broken? When I go to the /requests page and click to Accept a consultation, I am set as a consultant for that request and the status is set as ACCEPTED. Tested it and it works like that.

**Comment by salman-** [comment]
Make a request, including a comment, and text type and a file.
Now login and try to accept it

**Comment by TKasekamp** [comment]
Tested it like that and it works. Not that I'm testing locally with the latest version of the code.
