### ISSUE TITLE
make a visual on data on backend using devtool

### ISSUE THREAD

**Issue by salman-** [JaanJanno/ConsultationWeb#78]
Since we are going to change the status of consultants then, we have to be able to see the records.
Use [devtool ](https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-devtools/1.3.0.RELEASE) to make it visualize. @TKasekamp

**Comment by JaanJanno** [comment]
What exactly do you need this for? The data model for the consultant accounts isn't that complex yet.

IF you really need it, you can perhaps add it yourself?

**Comment by salman-** [comment]
@JaanJanno  Make a request, including a comment, and text type and a file.
Now login and try to accept it. If @TKasekamp  has a visual on data, maybe it would be easier for him to check it.

I am not going to do this  because it is definitely a back-end issue

**Comment by TKasekamp** [comment]
That comment is probably about another issue.

**Comment by TKasekamp** [comment]
Also, the REST API is still somewhat functional. For example in `/api/requests` you can see all the requests as they are in the database. You can use that to check if something worked. Note that all the API stuff will be removed by 3rd iteration date.
