### ISSUE TITLE
There is already 'feedbackController' bean method

### ISSUE THREAD

**Issue by salman-** [JaanJanno/ConsultationWeb#88]
I just pulled the repo, and realized that it does not boot.
Before every push, we should make sure everything is functional. @TKasekamp

**Comment by TKasekamp** [comment]
The latest version of the code works for me. Tested /report and /feedback (both served by FeedbackController) and everything works.

Do a hard reset and see if the issue is still there.

**Comment by salman-** [comment]
git reset --hard HEAD

Didn't work for me.
It simply falsify the last commit in my local repo. How does it suppose to solve such issue?
