### ISSUE TITLE
Make controller only for resources

### ISSUE THREAD

**Issue by salman-** [JaanJanno/ConsultationWeb#89]
The **Statistic** is not a resource, so we do not make a controller for it.  
It is just simple page to present statistic regarding the resources like **requests**. 
Upload, Feedback are also not resources.
What are the metrics to make a controller? @TKasekamp  @JaanJanno

**Comment by TKasekamp** [comment]
Then from where do you want to get the statistics page? The RequestController is already 150 lines long and will only get longer as all the meeting change stuff will go there. The Controllers must be kept to a maintainable size, that is also why I removed the feedback stuff from there. 

Statistics are best served from a dedicated controller.

**Comment by salman-** [comment]
You don't add an extra controller just because the previous one is 150 line.
Previously, you had 1 issue( a very big controller with 150 lines) and now, you not only solved that one but add an extra issue which is  an extra un-useful controller.

Once again the controllers could come from the resource model.

**Comment by TKasekamp** [comment]
Then where would you put the /statistics page? The controller methods for issues #71 and #73 ?

**Comment by TKasekamp** [comment]
We also have a LoginController, would you also get rid of it because there is no resource Login?

**Comment by salman-** [comment]
Did i say we should remove login controller? You can consider login as exception, but in login you should only have a get method to load the page. But, yes you are right. It does not make sense to have a controller for loggin. You can ask Luciano too.

If i were you, i wait for @JaanJanno  to draw the resource model, then based on it, the controllers should be developed.

**Comment by TKasekamp** [comment]
But still, from where would you serve the pages dealing with statistics?

**Comment by JaanJanno** [comment]
I think it's reasonable to have a separate controller for the statistics pages.

Luciano is not the customer. Let's keep it simple. The resource model is not gonna help you here either, because we need to put the "non-resources" somewhere too, don't we.

**Comment by salman-** [comment]
About login, if you want to be picky YES. you should remove it and instead use[ spring security](https://spring.io/guides/gs/securing-web/), and instead of controller use addViewControllers.
If you are not picky, then you are an easygoing person with your mistakes and tough with others!!!
So what is the strategy??? Be easygoing or be picky???? I can be both.

@JaanJanno  I am talking about a technical issue and not bossiness. and it is the thing that Luciano can make some advise. 

At this moment,  you derive this statistics from requests, right?
So,  it should be on the controller related to the requests.

**Comment by JaanJanno** [comment]
I'd call this controller placement a convention issue.

Not sure why you accuse me of pickiness. I don't think I've made anything but minor remarks about the parts of the front-end you made now with thyme-leaf. I even made the decision to have you use angular until the last minute back at the beginning per your request.

**Comment by salman-** [comment]
@JaanJanno  sorry man, you were not my audiance. I also accepted your leadership, because I trusted you. I should clarify my audiance.

I was talking with @TKasekamp , because in the last meeting he told me that, he is not satisfied with my efforts. Also, he said he is picky and bla bla bla. So @TKasekamp  is picky should be mostly tough with hisself too. Here is not a good place to struggle i will say the rest in meeting.

**Comment by JaanJanno** [comment]
It's ok.

About where to put those statistics views in controllers. I don't know. Either way I say, I'll shit in someones cereal, it seems. I don't want either of you guys to hate me in the end.

I still believe this is a convention issue. No real technical reason to go with either approach.  That's why my first thought was to leave it as it is.
Might as well toss a coin tomorrow. :D

**Comment by JaanJanno** [comment]
I'll close this for now.
I hope we have kind of reached an understanding.
