### ISSUE TITLE
Define REST API for calendar information retrieval.

### ISSUE THREAD

**Issue by JaanJanno** [JaanJanno/ConsultationWeb#91]
https://fullcalendar.io/

**Comment by JaanJanno** [comment]
Functional requirement 9, 26
https://github.com/JaanJanno/ConsultationWeb/wiki/Functional-requirements-and-vision

**Comment by TKasekamp** [comment]
Doing it myself as I want to work on calendar right now. `/calendar` for all meetings by every consultant. `/calendar/{id}` for meetings for consultant with this id. The object sent is CalendarDTO.

**Comment by TKasekamp** [comment]
Or some other API. I'll think about it.

**Comment by TKasekamp** [comment]
`/api/calendar` and `/api/calendar/{id}`. @JaanJanno , thanks for the help.
