### ISSUE TITLE
The uri accounts/manage does not receive the role

### ISSUE THREAD

**Issue by salman-** [JaanJanno/ConsultationWeb#93]
It seems that the left handside navigation menu in **accounts/manage** does not receive the **role** 
I do understand your control, and i don't want to change it.

**Comment by JaanJanno** [comment]
Can you specify a bit? Is it the "admin/manage_account" view? Regarding the controller "AccountController" method "ManagingAccounts" (why is this upper case by the way? :( )?

**Comment by JaanJanno** [comment]
Also, you can copy in your next comment the fragment you are trying to add into the html that does not find the role.

**Comment by TKasekamp** [comment]
@JaanJanno so you are handling this? If so remove me from this issue.

**Comment by JaanJanno** [comment]
Fine..
